---
title: "Data Import"
author: "Xiaoxue Yu"
date: "9/17/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
```


## Load in the litters data

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)
litters_data
```

## Load in the pups data


```{r}
pups_data = read_csv(file = "./data/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)
```


## Play with column parsing

```{r}
litters_data = read_csv(
  file = "./data/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  ))
```


## Read in an excel file ...

```{r}
mlb11_data_subset = 
  read_excel(
    path = "./data/mlb11.xlsx",
    range = "A1:D7")

write_csv(mlb11_data_subset, path = "./data/mlb_subset.csv")
```


## Read in SAS ...

```{r}
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat")
```


##data manipulating

```{r}
select(litters_data, group, litter_number)

select(litters_data,litter_number,gd0_weight,starts_with("pups"))

select(litters_data,litter_number, gd0_weight:pups_born_alive)

select(litters_data, GROUP=group, litter_number)

rename(litters_data, GROUP = group)
```


###filter!!!!
```{r}
filter(litters_data,group=="Mod8") ##logical operator, when its true, keep the row

filter(litters_data,gd_of_birth==20)

filter(litters_data,gd_of_birth>=20)

filter(litters_data,pups_born_alive <6, group == "Con7")

#how to say or?

drop_na(litters_data,gd0_weight) #drop rows with na in gd0_weight
```

#Some ways you might filter the litters data are
#gd_of_birth == 20
#pups_born_alive >= 2
#pups_survive != 4
#!(pups_survive == 4)
#group %in% c("Con7", "Con8")
##group == "Con7" & gd_of_birth == 20 ###


###mutate, add a column with calculation btw other columns

```{r}
mutate(litters_data,
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group),
  group = str_to_upper(group)
)

```

###arrange
```{r}
arrange(litters_data, group, pups_born_alive)

arrange(litters_data, desc(pups_born_alive))

arrange(litters_data,pups_born_alive, gd0_weight) 

```




###pipe  ##control shift M

```{r}
litters_data =
  read.csv("./data/FAS_litters.csv") %>% 
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) %>% 
  drop_na(wt_gain)
litters_data
```

```{r,eval= FALSE}
litters_data =
  read.csv("./data/FAS_litters.csv") %>% 
  janitor::clean_names(dat = .) %>%
  select(.data = .,-pups_survive) ##.data pull the last step's result
  lm(wt_gain ~ pups_born_alive, data = .)  ##what it means

```






